# This is a basic workflow to help you get started with Actions

name: Simple Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]
    steps:
      - name: Download code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install requests termcolor
      - name: Run Simple tests
        run: |
          cd tests
          python simple_tests.py
      - name: Archive results of a test run
        uses: actions/upload-artifact@v2
        with:
          name: tests_working_directory
          path: |
            tests/
            !tests/simple_tests.py

